# Generated by Django 4.1 on 2022-08-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timezone',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Часовой пояс'),
        ),
        migrations.AlterField(
            model_name='timezone',
            name='tag',
            field=models.CharField(max_length=15, verbose_name='Обозначение'),
        ),
        migrations.AlterField(
            model_name='timezone',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Наименование'),
        ),
    ]
