# Generated by Django 4.1 on 2022-08-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_timezone_code_alter_timezone_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timezone',
            name='code',
            field=models.CharField(max_length=5, verbose_name='Часовой пояс'),
        ),
        migrations.AlterField(
            model_name='timezone',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Наименование'),
        ),
    ]
