# Generated by Django 4.1 on 2022-08-30 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, null=True, verbose_name='Код мобильного оператора')),
                ('tag', models.CharField(max_length=15, null=True, verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Фильтр',
                'verbose_name_plural': 'Фильтры',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания рассылки')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('started', models.DateField(verbose_name='Дата отправки рассылки')),
                ('ended', models.DateField(verbose_name='Дата окончания рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Notice_Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice_table', to='notice.filter')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_table', to='notice.notice')),
            ],
        ),
    ]
