# Generated by Django 4.1 on 2022-08-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timezone',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Часовой пояс'),
        ),
    ]
