# Generated by Django 4.1 on 2022-08-25 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_alter_client_phone_alter_timezone_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='client',
        ),
        migrations.RemoveField(
            model_name='message',
            name='notice',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='TimeZone',
        ),
    ]
