# Generated by Django 4.1 on 2022-08-25 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_notice_filters_delete_notice_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='filters',
        ),
        migrations.CreateModel(
            name='Notice_Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice_table', to='notice.filter')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_table', to='notice.notice')),
            ],
        ),
    ]
